source 'https://rubygems.org'

group :development, :test do
  gem 'rspec'
  gem 'pact', path: '../../'
  gem 'pry'
end

gem 'rake', '>= 12.3.3'
gem 'rack', '~> 3.0', '>= 3.0.0'
gem 'json', '~> 2.3', '>= 2.3.0'
gem 'sqlite3'
gem 'sequel'
gem 'sinatra', '>= 2.2.3'
