source 'https://rubygems.org'

group :development, :test do
  gem 'rspec'
  gem 'pact', path: '../../'
  gem 'pact_broker-client', '>= 1.0.0'
  gem 'pry'
end

gem 'rake'
gem 'rack', '~> 2.2.20'
gem 'json', '~>1.6.8'
gem 'httparty'
